apiVersion: v1
kind: Pod
metadata:
  name: my-localhost-pod
spec:
  containers:
    - name: nginx
      image: nginx
    - name: another
      image: curlimages/curl
      command: [ "sh", "-c", "sleep 1000" ]