apiVersion: v1
kind: Pod
metadata:
  name: my-test-pod
spec:
  containers:
    - name: my-test-container
      image: nginx
      env:
        - name: SAMPLE_ENV
          value: "Hello world"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName