apiVersion: v1
kind: Pod
metadata:
  name: my-multi-pod
spec:
  initContainers:
    - name: my-init-container
      image: busybox
      command: ['sh', '-c', 'sleep 10']
  containers:
    - name: nginx
      image: nginx:1.24
    - name: redis
      image: redis