apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-500
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: host-pv
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /my-pv/data/pv1