apiVersion: v1
kind: Pod
metadata:
  name: my-pv-pod
spec:
  volumes:
    - name: my-pvc
      persistentVolumeClaim:
        claimName: my-pvc-100
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: my-pvc
          mountPath: /data/pv