apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-250
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: host-pv
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /my-pv/data/pv1